// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3t7m0Ux64Jl2vHo0vvE43beBodTp0Eao',
    appId: '1:202719522068:web:cabfdab59b52772fa8e601',
    messagingSenderId: '202719522068',
    projectId: 'analyticsflutter-b6d33',
    authDomain: 'analyticsflutter-b6d33.firebaseapp.com',
    storageBucket: 'analyticsflutter-b6d33.appspot.com',
    measurementId: 'G-B4H75TK4ZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-eNW_XOL2x4kSIJDUiUPFn1M4r7ovgYM',
    appId: '1:202719522068:android:e822a3f4e58f5e46a8e601',
    messagingSenderId: '202719522068',
    projectId: 'analyticsflutter-b6d33',
    storageBucket: 'analyticsflutter-b6d33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_WLBLFpmrfiazOE6acag9rbIgBlpGsZU',
    appId: '1:202719522068:ios:6ecca8fffd1faa39a8e601',
    messagingSenderId: '202719522068',
    projectId: 'analyticsflutter-b6d33',
    storageBucket: 'analyticsflutter-b6d33.appspot.com',
    iosClientId: '202719522068-k1of400vuka6du6c8chnrqv48l4fvmht.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAnalytics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_WLBLFpmrfiazOE6acag9rbIgBlpGsZU',
    appId: '1:202719522068:ios:6ecca8fffd1faa39a8e601',
    messagingSenderId: '202719522068',
    projectId: 'analyticsflutter-b6d33',
    storageBucket: 'analyticsflutter-b6d33.appspot.com',
    iosClientId: '202719522068-k1of400vuka6du6c8chnrqv48l4fvmht.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAnalytics',
  );
}
